name: pocket_pose
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  animated_bottom_navigation_bar: ^1.2.0

  flutter:
    sdk: flutter

  provider: ^6.0.5
  flutter_svg: ^2.0.5
  cupertino_icons: ^1.0.2
  google_mlkit_commons: ^0.3.0
  google_mlkit_pose_detection: ^0.6.0
  fluttertoast: ^8.2.2
  camera: ^0.10.4
  path_provider: ^2.0.15
  external_path: ^1.0.3
  http: ^0.13.5
  dio: ^5.0.3
  audio_session: ^0.1.15
  audioplayers: ^0.20.0
  video_player: ^2.6.1
  json_annotation: ^4.8.0
  change_app_package_name: ^1.1.0
  kakao_flutter_sdk_user: ^1.4.3
  package_info_plus: ^4.0.2
  flutter_secure_storage: ^8.0.0
  flutter_spinkit: ^5.2.0
  introduction_screen: ^3.1.9
  like_button: ^2.0.5
  semicircle_indicator: ^1.1.1
  image_picker: ^1.0.0
  textfield_tags: ^2.0.2
  permission_handler: ^10.4.2
  shared_preferences: ^2.2.0
  flutter_typeahead: ^4.6.2
  stomp_dart_client: ^0.4.4
  assets_audio_player: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - assets/audios/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: GmarketSans
      fonts:
        - asset: assets/fonts/GmarketSansTTFBold.ttf
        - asset: assets/fonts/GmarketSansTTFLight.ttf
        - asset: assets/fonts/GmarketSansTTFMedium.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
