// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'stage_skeleton.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

StageSkeleton _$StageSkeletonFromJson(Map<String, dynamic> json) =>
    StageSkeleton(
      noseX: (json['noseX'] as num).toDouble(),
      noseY: (json['noseY'] as num).toDouble(),
      noseZ: (json['noseZ'] as num).toDouble(),
      rightShoulderX: (json['rightShoulderX'] as num).toDouble(),
      rightShoulderY: (json['rightShoulderY'] as num).toDouble(),
      rightShoulderZ: (json['rightShoulderZ'] as num).toDouble(),
      rightElbowX: (json['rightElbowX'] as num).toDouble(),
      rightElbowY: (json['rightElbowY'] as num).toDouble(),
      rightElbowZ: (json['rightElbowZ'] as num).toDouble(),
      rightWristX: (json['rightWristX'] as num).toDouble(),
      rightWristY: (json['rightWristY'] as num).toDouble(),
      rightWristZ: (json['rightWristZ'] as num).toDouble(),
      rightHipX: (json['rightHipX'] as num).toDouble(),
      rightHipY: (json['rightHipY'] as num).toDouble(),
      rightHipZ: (json['rightHipZ'] as num).toDouble(),
      rightKneeX: (json['rightKneeX'] as num).toDouble(),
      rightKneeY: (json['rightKneeY'] as num).toDouble(),
      rightKneeZ: (json['rightKneeZ'] as num).toDouble(),
      rightAnkleX: (json['rightAnkleX'] as num).toDouble(),
      rightAnkleY: (json['rightAnkleY'] as num).toDouble(),
      rightAnkleZ: (json['rightAnkleZ'] as num).toDouble(),
      leftShoulderX: (json['leftShoulderX'] as num).toDouble(),
      leftShoulderY: (json['leftShoulderY'] as num).toDouble(),
      leftShoulderZ: (json['leftShoulderZ'] as num).toDouble(),
      leftElbowX: (json['leftElbowX'] as num).toDouble(),
      leftElbowY: (json['leftElbowY'] as num).toDouble(),
      leftElbowZ: (json['leftElbowZ'] as num).toDouble(),
      leftWristX: (json['leftWristX'] as num).toDouble(),
      leftWristY: (json['leftWristY'] as num).toDouble(),
      leftWristZ: (json['leftWristZ'] as num).toDouble(),
      leftHipX: (json['leftHipX'] as num).toDouble(),
      leftHipY: (json['leftHipY'] as num).toDouble(),
      leftHipZ: (json['leftHipZ'] as num).toDouble(),
      leftKneeX: (json['leftKneeX'] as num).toDouble(),
      leftKneeY: (json['leftKneeY'] as num).toDouble(),
      leftKneeZ: (json['leftKneeZ'] as num).toDouble(),
      leftAnkleX: (json['leftAnkleX'] as num).toDouble(),
      leftAnkleY: (json['leftAnkleY'] as num).toDouble(),
      leftAnkleZ: (json['leftAnkleZ'] as num).toDouble(),
    );

Map<String, dynamic> _$StageSkeletonToJson(StageSkeleton instance) =>
    <String, dynamic>{
      'noseX': instance.noseX,
      'noseY': instance.noseY,
      'noseZ': instance.noseZ,
      'rightShoulderX': instance.rightShoulderX,
      'rightShoulderY': instance.rightShoulderY,
      'rightShoulderZ': instance.rightShoulderZ,
      'rightElbowX': instance.rightElbowX,
      'rightElbowY': instance.rightElbowY,
      'rightElbowZ': instance.rightElbowZ,
      'rightWristX': instance.rightWristX,
      'rightWristY': instance.rightWristY,
      'rightWristZ': instance.rightWristZ,
      'rightHipX': instance.rightHipX,
      'rightHipY': instance.rightHipY,
      'rightHipZ': instance.rightHipZ,
      'rightKneeX': instance.rightKneeX,
      'rightKneeY': instance.rightKneeY,
      'rightKneeZ': instance.rightKneeZ,
      'rightAnkleX': instance.rightAnkleX,
      'rightAnkleY': instance.rightAnkleY,
      'rightAnkleZ': instance.rightAnkleZ,
      'leftShoulderX': instance.leftShoulderX,
      'leftShoulderY': instance.leftShoulderY,
      'leftShoulderZ': instance.leftShoulderZ,
      'leftElbowX': instance.leftElbowX,
      'leftElbowY': instance.leftElbowY,
      'leftElbowZ': instance.leftElbowZ,
      'leftWristX': instance.leftWristX,
      'leftWristY': instance.leftWristY,
      'leftWristZ': instance.leftWristZ,
      'leftHipX': instance.leftHipX,
      'leftHipY': instance.leftHipY,
      'leftHipZ': instance.leftHipZ,
      'leftKneeX': instance.leftKneeX,
      'leftKneeY': instance.leftKneeY,
      'leftKneeZ': instance.leftKneeZ,
      'leftAnkleX': instance.leftAnkleX,
      'leftAnkleY': instance.leftAnkleY,
      'leftAnkleZ': instance.leftAnkleZ,
    };
