// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-TNSnZHERZ8-UhiVppewkgKZFdIj68Bc',
    appId: '1:362925676787:web:ed73546bc1d3f6dd813f86',
    messagingSenderId: '362925676787',
    projectId: 'poket-pose',
    authDomain: 'poket-pose.firebaseapp.com',
    storageBucket: 'poket-pose.appspot.com',
    measurementId: 'G-92B37GNN18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAka6I1flS9pNf9h7VI1eMjtH-YMBDsV5E',
    appId: '1:362925676787:android:d867916660915a53813f86',
    messagingSenderId: '362925676787',
    projectId: 'poket-pose',
    storageBucket: 'poket-pose.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvM_1nxbDRn9zkAqPYQm048cYwM_8gSBY',
    appId: '1:362925676787:ios:8a5dee8589f3b17b813f86',
    messagingSenderId: '362925676787',
    projectId: 'poket-pose',
    storageBucket: 'poket-pose.appspot.com',
    iosClientId: '362925676787-5pa90752u4d6dmmimkobr2fk7lakeedu.apps.googleusercontent.com',
    iosBundleId: 'com.example.pocketPose',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvM_1nxbDRn9zkAqPYQm048cYwM_8gSBY',
    appId: '1:362925676787:ios:8a5dee8589f3b17b813f86',
    messagingSenderId: '362925676787',
    projectId: 'poket-pose',
    storageBucket: 'poket-pose.appspot.com',
    iosClientId: '362925676787-5pa90752u4d6dmmimkobr2fk7lakeedu.apps.googleusercontent.com',
    iosBundleId: 'com.example.pocketPose',
  );
}
